version: '2'

services:
    www:
        build: .
        image: srv/srv-www
        container_name: srv-www
        external_links:
            - srv-db
        volumes:
            - /srv/www/www:/srv/www
        restart: always
    adm:
        image: srv/srv-www
        container_name: srv-adm
        external_links:
            - srv/srv-db
        volumes:
            - /srv/www/adm:/srv/www
        restart: always
networks:
    default:
        external:
            name: lan
